name: Mirasol release

on:
  push:
    tags:
      - 'v*.*.*'    # Push of a v* tag

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: [ '1.19' ]
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
    - name: Install systemd lib dependencies
      run: |
        sudo apt update
        sudo apt install libsystemd-dev
    - name: Build
      run: VERSION=`git describe --tags --abbrev=8 --dirty --always --long` ; go build -ldflags "-extldflags=-static -X 'main.version=$VERSION'"
    - name: Checksum
      run:  shasum -a 256 -b mirasol > mirasol.sha256
    - uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        generate_release_notes: true
        files: |
          mirasol
          mirasol.sha256
          LICENSE
